### ISSUE TITLE
ip address

### ISSUE THREAD

**Issue by HakkaTjakka** [beatfreaker/subdownloader#12]
how to set ip address?

sd --deep
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 23.239.11.213:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:424:9)
    at Socket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '23.239.11.213',
  port: 80
}

**Comment by petref** [comment]
Did you managed to find the culprit on this one?
